name: template-module-placeholder
run-name: template-module-placeholder v${{ github.event.inputs.version }} (${{ github.ref_name }}) build ${GITHUB_RUN_NUMBER}
on: [push, pull_request]
jobs:
  quality-control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache-dependency-path: '**/go.sum'
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61
      - name: test with race detector
        run: go test -v --race ./...
      - name: test with coverage
        run: go test -v -coverprofile=coverage.out -covermode=atomic -coverpkg=./...
      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          config: ./.testcoverage.yml
      - name: generate coverage report
        run: go tool cover -html=coverage.out -o coverage.html
      - name: upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.html
    
      
    